apiVersion: v1
kind: Secret
metadata:
  name: parkflow-secrets
type: Opaque
stringData:
  db-username: postgres
  db-password: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parkflow-config
data:
  DB_HOST: parkflow-db
  DB_PORT: "5432"
  DB_NAME: parkflow
